"""IP-FC-21: the drawing's appearance, pinned as project data.

**Why this file exists.** `dimension_scheme.md` section 5 makes five hard constraints on where
a generated drawing puts its dimensions, and a build that violates one fails rather than
emitting the drawing. Three of them -- containment, text against text, text against geometry --
test the *rectangle an annotation occupies*, and nothing in a headless FreeCAD reports that
rectangle: `getArrowPositions()` returns the origin for both arrowheads, and no call reports
the text's rendered width. Both are computed by the GUI-side view provider, which does not
exist in a console application.

So the extent has to be known from the font. That is entirely tractable -- but only if the
font is known, and today it is not. Measured 2026-08-21 under `freecadcmd`: TechDraw's
`Labels`, `Dimensions` and `General` preference groups are **empty**, so the text is drawn with
a compiled-in default that a user preference can silently change, and the sheet template
resolves through `App.getResourceDir()` into the FreeCAD installation rather than into this
repository. **A placement bound taken from a font the reader's machine does not use is not a
bound.** This module pins both and checks the pin.

**Why the pin is checked rather than trusted.** The failure mode is the one this project keeps
meeting: a drawing built against the wrong metrics does not fail. It renders, it exports
byte-identically, it diffs cleanly, and it prints with two dimensions touching. There is no
symptom until someone reads a digit wrong. `verify_font` below recomputes the recorded numbers
from the font file actually found and refuses to proceed if they disagree -- the same shape as
`units.bbox_m_matches_mm`, and for the same reason.

**What is NOT in here, deliberately.** Nothing in this file reaches geometry, so none of it
belongs in `design_constants.json` -- that file's own membership test is "if a number reaches
an OpenSCAD module as a named argument", and a font does not. These are presentation
standards, and the sheet is where they end.

**Unit regime: millimeters**, per `units.py` -- everything here is a page dimension, and a page
is a FreeCAD-side object.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


# --------------------------------------------------------------------------------------
# The sheet
# --------------------------------------------------------------------------------------

# ANSI A landscape, 279.4 x 215.9 mm. Chosen because it is the smallest stock sheet that
# holds a family drawing's view plus its value table, and because the whole point of
# OQ-ARCH-7's family drawing is that one readable sheet replaces 576 crowded ones -- a
# larger sheet would be solving a problem the family drawing already solved.
# **The template is this project's, not the installation's, since IP-FC-86.** It used to
# resolve through `App.getResourceDir()` into the FreeCAD install, which was recorded as a
# finding at the time and not acted on: a generated drawing that depends on a file the project
# does not carry is not reproducible from the project, and two machines with different FreeCAD
# versions would emit different sheets from the same source. It is now beside this module and
# generated by `tools/make_sheet_template.py`, whose docstring carries the derivation.
TEMPLATE_RELPATH = ('templates', 'fuselage_ansi_a_landscape.svg')
TEMPLATE_WIDTH_MM = 279.4
TEMPLATE_HEIGHT_MM = 215.9

# The one thing the stock ASME template could not do, and the reason OQ-DES-D5's decision is
# worth more than the millimeters it recovered: **the sheet states its units**. A cell in a
# value table is a bare number and so is an annotation, so without this the drawing asserts
# nothing about what its numbers mean. It is fixed text rather than an editable field, because
# an editable field can be filled in blank and this must not be able to go missing --
# `verify_template` fails the build if the string is absent.
TEMPLATE_UNITS_TEXT = 'DIMENSIONS IN MILLIMETERS'

# The fields TechDraw fills in from the document. Named here so `verify_template` can refuse a
# template that has lost one, which would otherwise show up as a blank box on a printed sheet.
TEMPLATE_EDITABLE_FIELDS = ('DrawingTitle', 'PartNumber', 'Revision', 'Sheet', 'Material',
                            'Process', 'Scale', 'Size', 'DrawnBy', 'Date')

# The sheet's own geometry, read out of that SVG on 2026-08-22 and re-asserted by
# `verify_template`. Pinned for the same reason as the font metrics, and with the same
# consequence if it is wrong: a table sized against a frame the template does not have runs
# off the sheet or wastes half of it, and nothing complains either way.
#
# Recorded by element id rather than by ordinal, because a template edit that adds a
# rectangle would renumber the ordinals and silently move the frame.
#
#   frame        `rect3675`, the inner border everything is drawn inside
#   title block  `rect2985`, which occupies the bottom right of that frame
#
# Each is (x, y, width, height) in millimeters, in the template's own coordinates -- y
# downward from the top edge, as SVG counts it.
TEMPLATE_FRAME_ID = 'rect3675'
TEMPLATE_FRAME_MM = (20.107, 14.473, 239.52, 187.2)
TEMPLATE_TITLE_BLOCK_ID = 'rect2985'
TEMPLATE_TITLE_BLOCK_MM = (129.627, 155.673, 130.0, 46.0)

# --------------------------------------------------------------------------------------
# The value table's layout, decided in OQ-DES-D5 on 2026-08-22
# --------------------------------------------------------------------------------------

# **The requirement all four of these serve**: the drawn view takes at least this share of the
# frame, and the title block and the value table share what is left. It is stated as a
# fraction rather than as millimeters because it is the thing being held constant while the
# sheet size and the table's contents are not.
VIEW_SHARE = 0.75

#: Table text heights to try, largest first, when packing a family sheet's blocks into the
#: band beside the title block.
#:
#: **The lettering is what gives, and that is a decision rather than a shortcut.** The three
#: blocks a family sheet carries besides the view -- the value table, the dimension key and
#: the sheet-coverage block -- come to about 11,600 mm2 at ISO 3098's smallest 2.5 mm, and
#: the frame is 44,834 with 5,980 of it under the title block. For the view to have the 75 %
#: `VIEW_SHARE` asks for, the three of them have to fit 5,229 -- which is 45 % of the area
#: and so 67 % of the linear size, about 1.7 mm of text. Packing waste takes it to 1.4.
#:
#: A drawing whose geometry cannot be read is not saved by a legible table beside it. So the
#: search runs down this series until the blocks fit the band, and the sheet keeps its view.
TABLE_TEXT_HEIGHTS_MM = (2.5, 2.2, 2.0, 1.8, 1.6, 1.4, 1.2, 1.0)

# A value table's row pitch, as a multiple of *its* text height. **1.4, which is ISO 3098's
# minimum line spacing for type B lettering** -- the same standard the text heights come from,
# so it is a number the drawing convention fixes rather than one this module picks.
#
# **Two wrong values preceded it and both are worth recording.** It was 2.0, the pitch
# `dimension_placement.LANE_PITCH_HEIGHTS` puts between dimension lines, taken so the sheet
# would have one vertical rhythm rather than two -- an argument about how the sheet looks,
# made before anyone had measured what the rhythm cost. OQ-DES-D5 measured it and took it to
# **1.3**, which fit the band and is **below the standard's minimum**: the same 1.4 was cited
# three files away as ISO 3098's floor for note line spacing, and the table was set tighter
# than it to make an arithmetic problem go away. That is exactly what section 5.4 warns of --
# *the knobs get tuned per drawing until the rules no longer mean anything*.
#
# The arithmetic problem was real and had a different answer, below.
TABLE_ROW_PITCH_HEIGHTS = 1.4

# **And 1.4 is not enough on its own, because a table row is ruled and a line of prose is
# not.** ISO 3098's 1.4 is the minimum distance between two *baselines*, which keeps one line
# of text off the next. A table row additionally has a line drawn along its edge, and what
# must clear that line is the glyph box -- `EM_PER_TEXT_HEIGHT` cap heights tall, 1.328, so at
# a 1.4 pitch the box leaves 0.07 of a cap height, 0.18 mm, to the rule above and below.
# Rendered, that reads as a rule struck through the text: measured 2026-09-07, the first data
# row of every value table and the heading above it were both touching the rule between them.
#
# So a row clears its rules by this much on each side, and the pitch is whichever requirement
# is the stricter.
#
# **A quarter of a cap height, and the number is only meaningful because the cells are placed
# correctly.** Raising it to 0.4 was tried while the first data row of every block was touching
# the rule above it, and it did not help, because the row was not short of space: it was drawn
# half a cap height high, a `DrawViewAnnotation` being positioned by its baseline rather than
# by the middle of its text (see `drawing.add_table`). Widening a row to fix text that is
# outside its row is the kind of tuning section 5.4 warns about -- it would have left every
# table a third taller for nothing, and on these sheets that came straight out of the view,
# taking two bulkheads from 1:1 to 1:2. With the placement right, this leaves 1.08 mm of white
# between the ink and a rule drawn 0.76 mm thick.
TABLE_ROW_CLEARANCE_HEIGHTS = 0.25

# The same requirement on the other axis, and it had the same hole. `column_width_mm` returned
# exactly the width of the widest string a column prints, so the widest value in every column
# ran from one rule to the other with nothing between: measured 2026-09-07, all thirteen
# columns of the bulkhead table came out width == need, to the millimetre, and `0.75` in the
# `U` column drew across its own left-hand rule. A cell needs white space beside it for the
# same reason a row needs white space above it -- the rule is 0.76 mm of ink, and a gap
# narrower than that does not read as a gap.
TABLE_COLUMN_PADDING_HEIGHTS = 0.35

# The clear gap between two columns of a value table, in millimeters -- **not a multiple of
# the text height, and that is the correction**. This was one text height, taken from section
# 5.2's H2 on the reasoning that H2 requires one text height between two text blocks and a
# table column is a column of digits beside another column of digits.
#
# H2 governs annotations **floating on a view with nothing between them**, where the gap is
# the only thing separating two numbers. A table has a rule between its columns, which is what
# a rule is for. Applied where it does not apply, H2 was the single largest thing making the
# table too wide: it cost 25 mm on the widest family, more than every other compaction
# together.
#
# **That justification is a debt on the table renderer, not a free saving.** 1.0 mm between two
# columns of digits is 0.4 of a text height and it is only enough because a rule is drawn
# between them. A table drawn without rules at this gutter is the failure H2 describes, and the
# renderer does not exist yet -- so this is written down here rather than left as an assumption
# somebody would have to reconstruct from a number.
TABLE_COLUMN_GUTTER_MM = 1.0

# **The value table sets one size smaller than the view.** 2.5 mm is the next size down in ISO
# 3098's preferred series, not a fraction chosen to fit, and a table setting smaller than the
# annotations around it is what every title block and parts list on every drawing does -- a
# column of digits under a heading is read differently from a number floating beside a feature.
#
# It was the view's 3.5 mm until 2026-08-27, and that was never a decision: nothing chose it,
# the table simply inherited `TEXT_HEIGHT_MM` because there was one constant. The cost of the
# inheritance was the whole of a reported blocker -- at 3.5 mm the panelled corner's table is
# 138.9 mm into a 108.5 mm band, and at 2.5 mm it is **104.0 mm, which fits** -- so a value
# nobody had picked was about to buy a change to the shape of the drawing set.
#
# **This is also what pays for the row pitch above.** At 3.5 mm text and the standard's 1.4 h
# spacing the table is 49.0 mm deep against a 46.8 mm band; at 2.5 mm it is 35.0.
TABLE_TEXT_HEIGHT_MM = 2.5

# Where the sheet puts the table and the title block. **The view's share is a packing result
# and not an area subtraction**, because a view is a projection with a bounding box, so what
# it gets is the largest *rectangle* left once the other two are placed. Only these two leave
# a rectangle at all:
#
#   band    title block and table side by side across the bottom, the view full width above.
#           The band is as deep as the deeper of the two.
#   column  table stacked above the title block on one side, the view full height beside. The
#           column is as wide as the **wider** of the two, so a table narrower than the title
#           block gains nothing by being narrower.
#
# Measured 2026-08-22: the band gives the view 75.7 % and the column 38.4 %, on the same
# table. Which one is available is decided by whether the table fits beside the title block.
PLACEMENT_BAND = 'band'
PLACEMENT_COLUMN = 'column'


# --------------------------------------------------------------------------------------
# The font
# --------------------------------------------------------------------------------------

# osifont is the ISO 3098 drawing face TechDraw ships in its own resources. It is pinned by
# name here rather than left to the empty preference group, and `verify_font` asserts that
# what is installed is what was measured.
#
# It is NOT vendored into this repository. Vendoring raises a licensing question -- osifont
# is LGPL-3 with a font exception -- which belongs to IP-FC-6's survey and not to a drawing
# module. Referencing the installed copy and *checking its metrics* closes the same hole
# without taking that decision: a substituted or updated font fails the build loudly instead
# of quietly changing every annotation's width.
FONT_NAME = 'osifont'
FONT_RELPATH = ('Mod', 'TechDraw', 'Resources', 'fonts', 'osifont-lgpl3fe.ttf')

# ISO 3098 preferred text heights are 2.5, 3.5, 5, 7, 10, 14 and 20 mm. 3.5 mm is the
# smallest of those that stays legible in a reduced print, which is how a shop drawing is
# usually read.
TEXT_HEIGHT_MM = 3.5

# Recorded from the pinned font on 2026-08-21 and re-asserted on every build by
# `verify_font`. Advances are in font design units; divide by UNITS_PER_EM and multiply by
# the text height to get millimeters.
UNITS_PER_EM = 2048

# **A text height on a drawing is a cap height, not an em size, and the difference is 33%.**
# ISO 3098 specifies `h` as the height of a capital, and TechDraw honours that: it scales the
# font so the ascender comes out at the `TextSize` it is given. Measured in the rendered page,
# 2026-09-07: text set to 2.5 mm draws at a 3.3 mm em and text set to 3.5 mm draws at 4.7 mm,
# both of which are `h * UNITS_PER_EM / TYPO_ASCENDER_UNITS` to the rounding the SVG writes.
#
# Every width here is an advance in design units, and an advance is a fraction *of the em*.
# Multiplying it by `h` therefore under-measures every string by that same 33% -- which is why
# the first rendered sheets had a value table whose columns were a third too narrow for their
# own contents, numbers lapping over the rules and headings running into their neighbours.
# `osifont` declares no `sCapHeight`, so the ascender is the metric to use, and it is pinned
# and re-checked like the advances beside it.
TYPO_ASCENDER_UNITS = 1542
EM_PER_TEXT_HEIGHT = UNITS_PER_EM / float(TYPO_ASCENDER_UNITS)


# ----------------------------------------------------------------------------------------
# Precision
# ----------------------------------------------------------------------------------------

# How many decimal places a length carries, and it is pinned here for the same reason the
# font is: it is not in the document either. TechDraw's `FormatSpec` defaults to two places
# from a compiled-in default -- `spike_techdraw.py` measured a 20 mm distance coming back as
# `20.00 mm` with nothing in the project asking for that -- so the number of digits a shop
# reads is currently inherited from a preference group that is empty on this machine.
#
# Two places is also the right number rather than merely the observed one. The tightest fit
# in the design is `longeron_tolerance` at 0.05 mm and `panel_tolerance` at 0.1 mm, so a
# hundredth resolves every clearance the parts are built to; a third place would print
# floating-point residue as though it were intent.
#
# **This is a drawing property with a measurement consequence.** `drawing_families.py` asks
# whether a dimension is a function of one size axis, and the honest form of that question is
# *at the precision the sheet prints*: a field that varies by 1e-13 with panel thickness is
# not a panel-dependent dimension on a sheet that writes two decimals. So the same constant
# decides the table's shape and the annotation's text, and it must not be two answers.
DECIMAL_PLACES = 2


def format_length(value_mm, decimals=DECIMAL_PLACES):
    """A length as it is written on the sheet.

    One function so the table cell, the annotation text and the separability test cannot
    disagree about what number a variant shows. `-0.00` is normalized to `0.00`: the sign of
    a value that rounds to zero is floating-point residue, and a drawing that prints it is
    stating a direction it does not mean.
    """
    text = '%.*f' % (decimals, value_mm)
    if float(text) == 0.0:
        text = '%.*f' % (decimals, 0.0)
    return text


# --------------------------------------------------------------------------------------
# Callouts
# --------------------------------------------------------------------------------------

# OQ-ARCH-7's family drawing puts a lettered callout on the view and the values in a table,
# so the text on a view is one capital and the set of strings a drawing can contain is known
# before any variant is built. That is what makes the extent a bound rather than a
# measurement, and it is the whole reason the placement problem is tractable.
#
# I, O and Q are omitted, which is drafting convention rather than preference: I reads as 1,
# and O and Q read as 0. A callout the reader mistakes for a digit is worse than one letter
# less of alphabet.
CALLOUT_ALPHABET = 'ABCDEFGHJKLMNPRSTUVWXYZ'

# The widest glyph in that alphabet, W, at 1559 units. Every callout is bounded by this one
# number, and -- because every callout is the same length -- the bound is *uniform*. A
# uniform over-estimate shifts a layout; it does not distort it. That distinction is why the
# family drawing makes a conservative bound nearly free, where on variable-length value text
# it would reject layouts that would have placed cleanly.
WIDEST_CALLOUT_UNITS = 1559
WIDEST_CALLOUT_CHAR = 'W'


# --------------------------------------------------------------------------------------
# The value table
# --------------------------------------------------------------------------------------

# The table is the one place on the sheet where variable-length value text survives, so it
# does not get the callout bound. It does not need the collision machinery either: sizing a
# column is a grid problem, each column as wide as its widest cell.
#
# **osifont's digits are not tabular**, which is worth stating because it is the natural
# assumption for a drawing face and it is false here: '1' is 700 units and '8' is 1056, a
# 50 % spread. So a column cannot be sized by counting characters. Bounding each digit
# position by the widest digit is correct and cheap.
WIDEST_DIGIT_UNITS = 1056
WIDEST_DIGIT_CHAR = '8'
DECIMAL_POINT_UNITS = 412
MINUS_UNITS = 952


def resource_dir():
    """FreeCAD's installed data directory. Imported lazily so this module reads anywhere.

    `units.py` makes the same choice for the same reason: a module that states the project's
    conventions should be readable by any interpreter, not only by one with FreeCAD in it.
    """
    import FreeCAD as App
    return App.getResourceDir()


def template_path(resource=None):
    """Absolute path to the pinned sheet template, which lives in this repository.

    `resource` is accepted so a caller can point at another tree, and is *not* FreeCAD's
    resource directory any more -- the template is the project's own since IP-FC-86. The font
    still comes from the installation, deliberately: vendoring it raises a licensing question
    that belongs to IP-FC-6, and `verify_font` closes the same hole by asserting its metrics.
    """
    return os.path.join(resource or os.path.dirname(os.path.abspath(__file__)),
                        *TEMPLATE_RELPATH)


def font_path(resource=None):
    """Absolute path to the pinned drawing font."""
    return os.path.join(resource or resource_dir(), *FONT_RELPATH)


def table_region_mm(width_mm=None):
    """Where a value table goes, as (x, y, width, height) in template coordinates.

    **The table sits beside the title block in a band across the bottom of the frame**, which
    is what OQ-DES-D5 decided: it is the only placement that leaves the drawn view a rectangle
    of the share the requirement asks for. Its depth is `table_band_depth_mm`.

    **Its width is not pinned, and an early version of this function pinning it to the title
    block's was wrong.** That looked derived because on ANSI A the title block is 146.7 of the
    frame's 239.5 mm and dividing the sheet there is tidy. It is a coincidence of one paper
    size: the ASME title block is *the same 146.7 mm* on ANSI B, where the frame is 391.8, so
    the same rule would give a B-size sheet no more table than an A-size one. A rule that
    ignores the sheet it is applied to is not a derivation.

    Its width is its content's. An early version pinned it to the title block's, which looked
    derived and was a coincidence of one paper size -- the ASME block is *the same* 146.7 mm on
    ANSI B, where the frame is 391.8, so the rule would have given a B-size sheet no more table
    than an A-size one. A rule that ignores the sheet it is applied to is not a derivation.

    Pass a width to place a real table; pass none for the widest one the band can hold beside
    the title block.
    """
    frame_x, frame_y, frame_w, frame_h = TEMPLATE_FRAME_MM
    _block_x, _block_y, block_w, _block_h = TEMPLATE_TITLE_BLOCK_MM
    available = frame_w - block_w - TABLE_COLUMN_GUTTER_MM
    width = available if width_mm is None else float(width_mm)
    depth = table_band_depth_mm()
    return (frame_x, frame_y + frame_h - depth, width, depth)


def view_region_mm(table_width_mm=None):
    """Where the view and its annotations go, as (x, y, width, height).

    The frame less the table's actual width and one column gutter, at the frame's full height
    because the title block does not reach across it. With no table beside it -- the table on a
    sheet of its own -- the view has the whole frame.

    This width is the number section 5.2's H1 is actually tested against. Measured 2026-08-22
    on the corner: its family sheet, four OQ-DES-D2 notes and six dimensions, needs **84.5 mm**
    and its single-variant sheet needs **100.0 mm**, at the frame's full height. Those are what
    a table's width has to leave behind.
    """
    frame_x, frame_y, frame_w, frame_h = TEMPLATE_FRAME_MM
    if table_width_mm is None:
        return (frame_x, frame_y, frame_w, frame_h)
    gutter = TABLE_COLUMN_GUTTER_MM
    return (frame_x, frame_y, frame_w - float(table_width_mm) - gutter, frame_h)


def frame_region_mm():
    """The whole frame, as (x, y, width, height).

    The width budget when the table is on a sheet of its own rather than beside the view.
    """
    frame_x, frame_y, frame_w, frame_h = TEMPLATE_FRAME_MM
    return (frame_x, frame_y, frame_w, frame_h)


# ----------------------------------------------------------------------------------------
# Line weights, and where they have to be applied
# ----------------------------------------------------------------------------------------

# **ISO 128 line group 0.5**, which is the group that goes with 3.5 mm lettering: a wide line
# of 0.5 mm and a narrow one of 0.25, in a 2:1 ratio. Outlines are wide; everything that is
# not the part -- hidden edges, dimension and extension lines, leaders, the value table's own
# rules -- is narrow.
#
# **These are not properties of the drawing document, and that is the trap.** Line weight,
# dimension text size and hole centre marks live on TechDraw's *view providers*, which are Gui
# objects. The sheets are built by `freecadcmd`, which has none, so an `.FCStd` from this
# project carries no appearance at all and whatever opens it supplies the lot from compiled-in
# defaults. Measured 2026-09-07, those defaults are: every view drawn at **0.7 mm** including
# the value table's rules, dimension text at **5.0 mm** against the 3.5 this standard sets,
# and `ArcCenterMarks` **off**, so not one hole on any sheet had a centre mark. None of that
# was chosen; all of it was inherited. `freecad/render_pages.py` applies this table before it
# builds the page scene, which is the only moment at which these objects exist.
WIDE_LINE_MM = 0.5
NARROW_LINE_MM = 0.25

# The arrowhead. ISO 129 draws it about ten narrow-line-widths long, and it must not out-weigh
# 3.5 mm text sitting beside it.
ARROW_SIZE_MM = 2.5

#: How a view whose edges are table rules is named. Those are `DrawViewPart`s like the drawn
#: view -- see `drawing.add_table` for why the rules are real geometry -- so they cannot be
#: told apart by type, only by name, and they must not be drawn at outline weight. Matched by
#: suffix because there is more than one of them: the value table's and the dimension key's.
RULE_VIEW_SUFFIX = 'RuleView'


def view_appearance(name=None):
    """View-provider settings for a `DrawViewPart`, as {property: value}.

    Pass the object's name so the value table's rule view gets narrow lines: its edges are a
    table, not an outline, and at outline weight the rules out-weigh the numbers between them.
    """
    if name and name.endswith(RULE_VIEW_SUFFIX):
        return {'LineWidth': NARROW_LINE_MM,
                'HiddenWidth': NARROW_LINE_MM,
                'IsoWidth': NARROW_LINE_MM,
                'ArcCenterMarks': False}
    return {'LineWidth': WIDE_LINE_MM,
            'HiddenWidth': NARROW_LINE_MM,
            'IsoWidth': NARROW_LINE_MM,
            # **Off, and the marks are drawn instead.** `ArcCenterMarks` is one switch for the
            # whole view: it marks every arc the projection produced, which on a bulkhead means
            # every fillet and every lead-in as well as the four bores and the four bolts. A
            # centre mark asserts an axis a feature is located from, and a fillet has no such
            # axis -- the marks on them are noise sitting exactly where the located features
            # are, which is the worst place for it. There is no per-arc control, so the switch
            # goes off and `sheet_annotations` names the axes that get one.
            'ArcCenterMarks': False,
            'CenterScale': 1.0}


# ---------------------------------------------------------------------------------------
# Construction geometry: centre marks, centre lines, and the outlines of adjacent parts
# ---------------------------------------------------------------------------------------
#
# **These are cosmetic edges, and a cosmetic edge carries its own format in the document.**
# That is the whole reason this is possible headlessly. Line weight on a *view* is a
# view-provider property and a document built by `freecadcmd` has none -- which is why
# `view_appearance` above exists and has to be applied by the renderer. A cosmetic edge's
# style, weight, colour and visibility live in the edge itself, in the saved file, so
# construction geometry drawn here looks the same wherever the page is opened.
#
# Verified 2026-09-07 against FreeCAD 1.1.3: `CosmeticEdge.Format` is a dict with the keys
# `style`, `weight`, `color`, `visible`, lowercase. Capitalised keys are rejected.

#: ISO 128 line types, as the `style` a `CosmeticEdge.Format` takes. Qt pen-style numbering,
#: which is what TechDraw stores.
LINE_CONTINUOUS = 1
LINE_DASHED = 2
LINE_DOTTED = 3
#: Long-dash dotted: ISO 128 type G, the centre line.
LINE_CENTER = 4
#: Long-dash double-dotted: ISO 128 type K, which is what an adjacent part is drawn in.
LINE_PHANTOM = 5

#: Ink for construction geometry. Black, like everything else the sheet prints -- a
#: construction line is distinguished by its *dash pattern*, which survives a photocopier and
#: a monochrome plot, and not by being grey, which does not.
CONSTRUCTION_COLOR = (0.0, 0.0, 0.0, 1.0)

#: How far a centre mark's arms reach past the feature they mark, as a fraction of its radius.
#: ISO 128 draws them a short way clear of the circle so the cross reads as belonging to it
#: rather than as part of it.
CENTER_MARK_OVERRUN = 1.35

#: How far a centre line runs past the geometry it is an axis of, in text heights. Enough to
#: read as a line rather than as a scratch, and short enough not to reach the frame.
CENTER_LINE_OVERRUN_HEIGHTS = 1.5


def center_mark_format():
    """The format a centre mark's arms are drawn in.

    **Continuous, not dash-dotted, and the reason is the scale the arms come out at.** A mark
    is a short cross -- a bore of R2.05 gives arms 2.77 mm long in the model, which at the
    bulkhead's 1:2 is 1.4 mm on the paper. A long-dash dotted pattern needs several
    millimetres to read as a pattern; below that it renders as a dot, a gap, or nothing at
    all, and a centre mark that sometimes disappears is worse than none. The long lines --
    the symmetry axes, where the pattern is what distinguishes an axis from an edge -- get
    the dashes.
    """
    return {'style': LINE_CONTINUOUS, 'weight': NARROW_LINE_MM,
            'color': CONSTRUCTION_COLOR, 'visible': True}


def center_line_format():
    """The format a symmetry axis is drawn in: long-dash dotted, ISO 128 type G."""
    return {'style': LINE_CENTER, 'weight': NARROW_LINE_MM,
            'color': CONSTRUCTION_COLOR, 'visible': True}


def detail_marker_format():
    """The format the circle round a detail's region is drawn in on the plan.

    Continuous and narrow, which is how ISO 128 draws a detail boundary -- it is a statement
    about the drawing rather than about the part, and a dashed one would read as a hidden
    feature at exactly the place a reader is being asked to look.
    """
    return {'style': LINE_CONTINUOUS, 'weight': NARROW_LINE_MM,
            'color': CONSTRUCTION_COLOR, 'visible': True}


def phantom_format():
    """The format an adjacent part's outline is drawn in.

    Narrow, because it is not this part's material -- a reference outline at outline weight
    reads as a feature of the part being made, which is the one thing it must not do.
    """
    return {'style': LINE_PHANTOM, 'weight': NARROW_LINE_MM,
            'color': CONSTRUCTION_COLOR, 'visible': True}


def dimension_appearance():
    """View-provider settings for a `DrawViewDimension`."""
    return {'Fontsize': TEXT_HEIGHT_MM,
            'Arrowsize': ARROW_SIZE_MM,
            'LineWidth': NARROW_LINE_MM,
            'Font': FONT_NAME}


def leader_appearance():
    """View-provider settings for a `DrawLeaderLine`."""
    return {'LineWidth': NARROW_LINE_MM}


def table_row_pitch_mm(text_height_mm=None):
    """The distance between two rows of a value table, in millimeters.

    The larger of two requirements, not a choice between them: ISO 3098's baseline spacing,
    and the room a ruled row needs for its glyph box to clear the rules on either side. On
    this font and text height the second is the binding one, at 4.57 mm against 3.50.

    **It takes the height it is spacing.** Both terms are multiples of the text height, so a
    table laid out at a smaller lettering must be spaced at that lettering too -- read from
    the module constant instead, a block searched down the height series kept its depth while
    its width shrank, and the search could not find a packing that existed.
    """
    height = TABLE_TEXT_HEIGHT_MM if text_height_mm is None else float(text_height_mm)
    line_spacing = TABLE_ROW_PITCH_HEIGHTS * height
    ruled_row = ((EM_PER_TEXT_HEIGHT + 2.0 * TABLE_ROW_CLEARANCE_HEIGHTS) * height)
    return max(line_spacing, ruled_row)


def table_band_depth_mm():
    """How deep the band holding the title block and the value table may be, in millimeters.

    **This replaced a taller and wrong number when OQ-DES-D5 landed.** It used to be
    the frame's top edge down to the title block -- 139.0 mm, on the assumption that the
    table is a column beside the view and above the block. Under the decided layout the
    table is *beside* the block in a band across the bottom, and the band's depth is one
    minus the view's share. So
    the table went from 19 rows of budget to 10, and the 19 was never a budget the sheet had:
    it was the budget a different placement would have had.
    """
    return (1.0 - VIEW_SHARE) * TEMPLATE_FRAME_MM[3]


def table_column_height_mm():
    """Deprecated name for `table_band_depth_mm`, kept while callers move over."""
    return table_band_depth_mm()


def table_width_available_mm(view_width_mm):
    """How much width a value table has, given what a view beside it needs.

    **The budget nothing checked until 2026-08-22.** `table_rows_available` answered how tall a
    factored family table may be and every one of the thirteen families passed; the same table
    also has a width, and against this budget none of them passed carrying every field the part
    is driven by. That was [OQ-DES-D5](../../../doc/design/dimension_scheme.md#open-questions).

    Kept for the column placement, where the table and the view are genuinely side by side. In
    the band placement, which OQ-DES-D5 produces, the table is not beside the view at all
    and `best_view` is the function to ask.
    """
    return TEMPLATE_FRAME_MM[2] - float(view_width_mm) - TABLE_COLUMN_GUTTER_MM


def table_height_mm(rows, text_height_mm=None):
    """How deep a value table of `rows` printed rows is."""
    height = TABLE_TEXT_HEIGHT_MM if text_height_mm is None else text_height_mm
    return rows * TABLE_ROW_PITCH_HEIGHTS * height


def format_column(values, decimals=DECIMAL_PLACES):
    """A column of lengths, at the fewest decimal places that loses none of them.

    **Per column, not per value**, decided in OQ-DES-D5: a column whose decimal points do not
    line up is harder to read than one a character wider, and a table column is sized once for
    every row in it anyway.

    `DECIMAL_PLACES` is a **bound** on the precision a value may carry, and reading it as an
    instruction to print that many places whatever the value is made a column of 4.00, 10.00,
    5.00 spend six characters where one would do. `format_length` still prints the bound,
    because an annotation on a view is one number with nothing to line up against.
    """
    try:
        lengths = [float(v) for v in values]
    except (TypeError, ValueError):
        # A key column holds axis values, and a panel stock is named `1/16in` rather than
        # measured. Not an error: a column of names has no decimal places to drop, and
        # refusing here would make every caller ask what kind of column it has before
        # asking how to print it.
        return [str(v) for v in values]
    for places in range(0, decimals + 1):
        rendered = [format_length(v, places) for v in lengths]
        if all(float(r) == v for r, v in zip(rendered, lengths)):
            return rendered
    return [format_length(v, decimals) for v in lengths]


def best_view(table_w, table_h, block_w, block_h, frame_w=None, frame_h=None):
    """The largest rectangular view the sheet can hold, and how the rest is placed.

    **The view's share is a packing result, not an area subtraction** -- a view is a projection
    with a bounding box, so what it gets is the largest *rectangle* left once the title block
    and the value table are placed. Summing areas instead says the view has 90 % of the frame
    where the rectangle it can actually occupy is 38 %.

    Returns (placement, width, height, area, band depth, column width). `PLACEMENT_BAND` puts
    the title block and the table side by side across the bottom, the view full width above.
    `PLACEMENT_COLUMN` stacks them on one side, the view full height beside, and is as wide
    as the **wider** of the two, so a table narrower than the title block gains nothing
    by being narrower. The band is offered only when the table fits beside the block, which
    on the stock ANSI A template it does not: 146.7 mm of block leaves 91.9 mm, and the
    compacted table is 95.1.
    """
    frame_w = TEMPLATE_FRAME_MM[2] if frame_w is None else frame_w
    frame_h = TEMPLATE_FRAME_MM[3] if frame_h is None else frame_h
    gutter = TABLE_COLUMN_GUTTER_MM

    options = []
    if table_w <= 0.0:
        options.append((PLACEMENT_BAND, frame_w, frame_h - block_h, block_h, 0.0))
    else:
        if block_w + gutter + table_w <= frame_w:
            depth = max(block_h, table_h)
            options.append((PLACEMENT_BAND, frame_w, frame_h - depth, depth, 0.0))
        column = max(block_w, table_w)
        options.append((PLACEMENT_COLUMN, frame_w - column - gutter, frame_h, 0.0, column))

    best = None
    for name, width, height, depth, column in options:
        if width <= 0.0 or height <= 0.0:
            continue
        if best is None or width * height > best[3]:
            best = (name, width, height, width * height, depth, column)
    return best or ('none', 0.0, 0.0, 0.0, 0.0, 0.0)


def title_block_envelope(table_w, table_h, frame_w=None, frame_h=None, share=VIEW_SHARE):
    """The largest title block that still leaves the view its share, as (width, depth).

    **This is what OQ-DES-D5 specifies**, and it is a rectangle rather than a size. In the band
    placement the view is the full width above a band as deep as the deeper of the table
    and the block, so the depth is bounded by the share and the width by what the table
    leaves. Any
    block inside the envelope gives the *same* view share, because past the point where the
    block is shallower than the table the band's depth is the table -- which is why
    120 x 40 and 100 x 32 measure identically.

    On ANSI A landscape with the compacted table this is **143.4 x 46.8 mm**; the stock
    ASME block misses it by 3.2 mm of width and 1.3 mm of depth.

    Returns None where the table alone is deeper than the band may be, which would mean the
    share is unreachable however small the block is.
    """
    frame_w = TEMPLATE_FRAME_MM[2] if frame_w is None else frame_w
    frame_h = TEMPLATE_FRAME_MM[3] if frame_h is None else frame_h
    depth = (1.0 - share) * frame_h
    if table_h > depth:
        return None
    return (frame_w - TABLE_COLUMN_GUTTER_MM - table_w, depth)


def column_width_mm(cells, text_height_mm=None):
    """The width one value-table column needs, in millimeters.

    Pass every string that has to fit in the column, its heading included. The floor is a
    callout letter, because on a family sheet the heading *is* a callout letter and a column
    narrower than its own heading is not a column.

    Cells are measured exactly rather than bounded by `digits_width_mm`. A column is sized
    once against a set of values that is known in full -- the family's variants -- so there is
    nothing to be conservative about, and the bound costs real millimeters on a sheet where
    width turns out to be the binding constraint.

    **Plus padding, which is not slack.** Measuring the widest string exactly and stopping
    there gives a column the string fills to both edges, and the edges are ruled: the value
    touches the rule on one side and the rule is thicker than the gap on the other. The
    padding is `TABLE_COLUMN_PADDING_HEIGHTS` on each side, the horizontal twin of the
    clearance a row gets above and below.
    """
    height = TABLE_TEXT_HEIGHT_MM if text_height_mm is None else text_height_mm
    widths = [callout_width_mm(height)]
    widths += [text_width_mm(str(cell), height) for cell in cells]
    return max(widths) + 2.0 * TABLE_COLUMN_PADDING_HEIGHTS * height


def table_width_mm(columns, text_height_mm=None):
    """The width a value table needs: its columns, plus one gutter between each pair.

    `columns` is a sequence of column widths in millimeters, as `column_width_mm` returns.
    """
    columns = list(columns)
    if not columns:
        return 0.0
    gutter = TABLE_COLUMN_GUTTER_MM
    return sum(columns) + gutter * (len(columns) - 1)


def table_rows_available(text_height_mm=None):
    """How many printed rows a value table may have before the drawn view loses its share.

    Derived rather than estimated at every step, and every step has moved: OQ-DES-D1 was filed
    against "about 25", a guess at a sheet nobody had opened; measuring the frame and the title
    block gave **19**; and OQ-DES-D5 putting the table beside the title block rather than above
    it gives **10**, because the band it sits in may only be as deep as the quarter
    of the frame the view does not get.

    **It says 10 above and it returns 13, measured 2026-09-06, and the 10 is the stale
    one.** The band budget is 46.80 mm and a row is `TABLE_ROW_PITCH_HEIGHTS *
    TABLE_TEXT_HEIGHT_MM` = 3.50 mm, so 13 fit; the 10 dates from before the compaction
    ladder took the pitch from 2.0 heights to 1.4 and was never brought forward with it. The
    claim that an eleventh row takes the view to 73.3 % does not reproduce either: `best_view`
    puts the table *beside* a title block 46.0 mm deep, so the band depth is set by the block
    until the table passes it, and rows 11, 12 and 13 cost the view **nothing** -- it stays at
    75.4 %. The 14th is the one that bites, at 73.8 %, which fails DRW-9.

    So the sheet has **three spare rows**, not none. That matters because two work items were
    filed treating this as a hard constraint, and a budget believed to be exhausted forecloses
    designs that in fact fit -- see IP-FC-128.

    **Width, not depth, is where this sheet is actually tight**, and it is a cliff rather than
    a slope: the band placement needs `block + gutter + table` inside the frame, which leaves
    **12.0 mm** of table width spare. Two millimetres past that the layout falls back to a
    column and the view collapses from 75.4 % to **45.3 %**.
    """
    height = TABLE_TEXT_HEIGHT_MM if text_height_mm is None else text_height_mm
    return int(table_band_depth_mm() // (TABLE_ROW_PITCH_HEIGHTS * height))


def read_template_rect(text, element_id):
    """One rectangle out of a template SVG, as (x, y, width, height) in millimeters.

    The template's `viewBox` is in millimeters and its `width` is stated in millimeters, so
    the user unit is the millimeter and no scaling applies. `verify_template` checks that
    rather than assuming it -- a template authored at another scale would report a frame of
    plausible numbers in the wrong unit.
    """
    import re

    match = re.search('<rect[^>]*id="%s"[^>]*>' % re.escape(element_id), text)
    if match is None:
        return None
    attributes = dict(re.findall('([a-zA-Z-]+)="([^"]*)"', match.group(0)))
    try:
        return tuple(float(attributes[k]) for k in ('x', 'y', 'width', 'height'))
    except (KeyError, ValueError):
        return None


def verify_template(path=None):
    """Assert the installed sheet template is the one these constants were measured from.

    Returns a list of complaints, empty when the pin holds -- the same contract as
    `verify_font`, and called from the same place.
    """
    import re

    path = path or template_path()
    problems = []

    if not os.path.isfile(path):
        return ['the pinned sheet template is not at %s' % path]

    with open(path, encoding='utf-8') as handle:
        text = handle.read()

    header = re.search('<svg[^>]*>', text)
    attributes = dict(re.findall('([a-zA-Z:-]+)="([^"]*)"',
                                 header.group(0) if header else ''))
    if attributes.get('width') != '%gmm' % TEMPLATE_WIDTH_MM:
        problems.append('the template is %r wide, not %g mm -- every figure below is in the '
                        'template user unit, and that is the millimeter only if this says so'
                        % (attributes.get('width'), TEMPLATE_WIDTH_MM))
    if attributes.get('viewBox') != '0 0 %g %g' % (TEMPLATE_WIDTH_MM, TEMPLATE_HEIGHT_MM):
        problems.append('the template viewBox is %r, not the %g x %g the recorded rectangles '
                        'were read in' % (attributes.get('viewBox'), TEMPLATE_WIDTH_MM,
                                          TEMPLATE_HEIGHT_MM))

    for element_id, recorded, what in (
            (TEMPLATE_FRAME_ID, TEMPLATE_FRAME_MM, 'drawing frame'),
            (TEMPLATE_TITLE_BLOCK_ID, TEMPLATE_TITLE_BLOCK_MM, 'title block')):
        found = read_template_rect(text, element_id)
        if found is None:
            problems.append('the template has no rectangle %r, which is where the %s was '
                            'measured' % (element_id, what))
        elif any(abs(a - b) > 5e-3 for a, b in zip(found, recorded)):
            problems.append('the %s %r is at %s, not the recorded %s -- a table sized against '
                            'it would not fit the sheet' % (what, element_id, found, recorded))

    if TEMPLATE_UNITS_TEXT not in text:
        problems.append('the template does not say %r anywhere. A value table cell is a bare '
                        'number and so is an annotation, so a sheet without this asserts '
                        'nothing about what its numbers mean.' % TEMPLATE_UNITS_TEXT)

    missing = [f for f in TEMPLATE_EDITABLE_FIELDS
               if 'freecad:editable="%s"' % f not in text]
    if missing:
        problems.append('the template has no editable field for %s, which would print as an '
                        'empty box rather than fail' % ', '.join(missing))

    envelope = title_block_envelope(95.1, table_height_mm(10))
    block = TEMPLATE_TITLE_BLOCK_MM
    if envelope is None or block[2] > envelope[0] or block[3] > envelope[1]:
        problems.append(
            'the title block is %.1f x %.1f mm, outside the %s OQ-DES-D5 requires '
            '-- the drawn view would not reach %.0f%% of the frame'
            % (block[2], block[3], envelope, 100.0 * VIEW_SHARE))
    return problems


def mm_from_units(units, text_height_mm=TEXT_HEIGHT_MM):
    """Convert a font advance in design units to millimeters at a given text height.

    `text_height_mm` is a **cap height**, which is what a drawing standard means by a text
    height and what TechDraw renders it as. An advance is a fraction of the *em*, and the em
    is `EM_PER_TEXT_HEIGHT` times taller than the cap, so that factor belongs here -- once,
    at the single point where design units become millimetres, rather than at each of the
    three callers that would each be a chance to forget it.
    """
    return units / float(UNITS_PER_EM) * text_height_mm * EM_PER_TEXT_HEIGHT


def callout_width_mm(text_height_mm=TEXT_HEIGHT_MM):
    """The bound on a lettered callout's width. The same for every callout on the sheet."""
    return mm_from_units(WIDEST_CALLOUT_UNITS, text_height_mm)


def digits_width_mm(digit_positions, decimals=0, negative=False,
                    text_height_mm=TEXT_HEIGHT_MM):
    """A bound on the width of a numeric value-table cell.

    Bounds each digit position by the widest digit rather than rendering the actual number,
    so a column sized with this holds every value that will ever appear in it -- which is
    what a column needs, since the column is sized once and the rows are the variants.
    """
    units = digit_positions * WIDEST_DIGIT_UNITS
    if decimals:
        units += DECIMAL_POINT_UNITS
    if negative:
        units += MINUS_UNITS
    return mm_from_units(units, text_height_mm)


_ADVANCE_CACHE = {}


def text_width_mm(text, text_height_mm=TEXT_HEIGHT_MM, path=None):
    """The exact rendered width of a string in the pinned font.

    **This is for the single-variant sheets, not the family sheets.** A family sheet's view
    carries one lettered callout per dimension, so `callout_width_mm` bounds every annotation
    with one number and the bound is uniform. A single-variant sheet carries the *value* --
    `112.50` is about five times the width of `W` -- so its annotations differ from each other,
    and a uniform bound would either be useless or reject layouts that fit. Measuring each
    string exactly is what the second product needs, and it costs a dictionary lookup.

    Kerning is not applied. For digits, a decimal point and a space -- which is all a dimension
    value contains -- osifont defines no kern pairs, so the sum of advances is the rendered
    width rather than an approximation of it.
    """
    path = path or font_path()
    cache = _ADVANCE_CACHE.get(path)
    if cache is None:
        cache = {}
        _ADVANCE_CACHE[path] = cache
    unknown = [c for c in text if c not in cache]
    if unknown:
        advances, _ = measure_advances(path, ''.join(sorted(set(unknown))))
        cache.update(advances)
    return mm_from_units(sum(cache[c] for c in text), text_height_mm)


def measure_advances(path, chars):
    """Advance widths in design units for `chars`, read from the font file.

    Requires `fontTools`, which is present in FreeCAD's own Python (4.61.1 as of 1.1.1) and
    is not a project dependency -- drawings are built under `freecadcmd`, so that is where
    this runs. A missing glyph is an error rather than a zero: a zero-width character would
    silently shrink every bound that used it.
    """
    from fontTools.ttLib import TTFont

    font = TTFont(path, fontNumber=0)
    cmap = font.getBestCmap()
    hmtx = font['hmtx']
    units_per_em = font['head'].unitsPerEm

    advances = {}
    missing = []
    for char in chars:
        glyph = cmap.get(ord(char))
        if glyph is None:
            missing.append(char)
            continue
        advances[char] = hmtx[glyph][0]
    if missing:
        # Named by codepoint, not by the character. A build log is not guaranteed to be
        # UTF-8 -- FreeCAD's console on Windows is cp1252 -- and an error message that
        # cannot be printed is an error message that does not exist.
        raise ValueError(
            '%s has no glyph for %s. A missing glyph measures as zero width, which would '
            'silently shrink every placement bound derived from it.'
            % (os.path.basename(path),
               ', '.join('U+%04X' % ord(c) for c in missing)))
    return advances, units_per_em


def verify_font(path=None):
    """Assert that the installed font is the one these constants were measured from.

    Returns a list of complaints, empty when the pin holds. Equality is required rather than
    a mere upper bound: a font that got *narrower* would not break a layout, but it would
    mean the recorded numbers no longer describe the file, and the next person to widen
    something would be reasoning from stale measurements.
    """
    path = path or font_path()
    problems = []

    if not os.path.isfile(path):
        return ['the pinned font is not at %s -- TechDraw would fall back to a face whose '
                'metrics nothing here describes' % path]

    advances, units_per_em = measure_advances(path, CALLOUT_ALPHABET)

    if units_per_em != UNITS_PER_EM:
        problems.append('unitsPerEm is %d, not the recorded %d, so every millimeter figure '
                        'in this module is scaled wrong' % (units_per_em, UNITS_PER_EM))

    widest = max(advances, key=lambda c: advances[c])
    if advances[widest] != WIDEST_CALLOUT_UNITS or widest != WIDEST_CALLOUT_CHAR:
        problems.append(
            'the widest callout is %r at %d units, not the recorded %r at %d -- the '
            'placement bound no longer covers every letter'
            % (widest, advances[widest], WIDEST_CALLOUT_CHAR, WIDEST_CALLOUT_UNITS))

    ascender = typo_ascender_units(path)
    if ascender != TYPO_ASCENDER_UNITS:
        problems.append(
            'the typographic ascender is %d units, not the recorded %d -- every text width '
            'in this module is scaled by the em-to-cap-height ratio, so a column would be '
            'sized for a string narrower or wider than the one that gets drawn'
            % (ascender, TYPO_ASCENDER_UNITS))

    digits, _ = measure_advances(path, '0123456789')
    widest_digit = max(digits, key=lambda c: digits[c])
    if digits[widest_digit] != WIDEST_DIGIT_UNITS or widest_digit != WIDEST_DIGIT_CHAR:
        problems.append(
            'the widest digit is %r at %d units, not the recorded %r at %d -- value-table '
            'columns would be sized too narrow'
            % (widest_digit, digits[widest_digit], WIDEST_DIGIT_CHAR, WIDEST_DIGIT_UNITS))

    return problems


def typo_ascender_units(path=None):
    """The font's typographic ascender in design units.

    Read from `OS/2` rather than `hhea`: `hhea.ascent` on this face is 2697 units, which is
    the line-box ascent and includes room for accents, while `sTypoAscender` at 1542 is the
    height of a capital. Using the line-box number would over-measure every string by 75%
    instead of under-measuring it by 33%.
    """
    from fontTools.ttLib import TTFont

    font = TTFont(path or font_path(), fontNumber=0)
    return int(font['OS/2'].sTypoAscender)


def require_font(path=None):
    """`verify_font`, but raising. Call this before building a drawing, not after."""
    _require(verify_font(path), 'the pinned drawing font does not match its recorded metrics')


def require_template(path=None):
    """`verify_template`, but raising."""
    _require(verify_template(path),
             'the pinned sheet template does not match its recorded geometry')


def require_standard():
    """Everything the sheet is pinned to, checked in one call before a drawing is built."""
    require_font()
    require_template()


def _require(problems, headline):
    if problems:
        raise ValueError(headline + ':' + chr(10)
                         + chr(10).join('  - ' + p for p in problems))
