"""IP-FC-21: can TechDraw be driven from `freecadcmd`, with no GUI?

UC-7a wants a family drawing per part kind -- lettered dimension callouts over a
per-variant value table -- generated by the sweep. The sweep is a batch process, so
every step has to run without a window, and TechDraw is the workbench in this project
most obviously written for one: dimensions are normally placed by dragging them.

What the drawing loop needs, and none of it is answered by the workbench documentation:

    1. import TechDraw at all, and get a page with a real template on it
    2. project a view and read the resulting 2D geometry back as coordinates,
       because a placer that cannot see the drawing cannot avoid it
    3. bind a dimension to points computed from parameters rather than to a
       projected edge index, which IP-FC-5 showed varies with U
    4. read the dimension's own geometry back, because the checker in
       dimension_scheme.md section 5.6 is independent of the placer and has to
       measure what the placer produced
    5. write the finished page out, in a format a review can diff

Run:

    freecadcmd spike_techdraw.py

The assertions below are the answers, not the printout. A reader who wants the
findings rather than the evidence should read the IP-FC-21 row in
doc/implementation/freecad_migration.md.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import FreeCAD as App

from corner_common import is_entry_point

V = App.Vector

# The test box is 20 x 10 x 5 mm and the view is drawn at 2:1. Two numbers that differ
# matter here: a dimension has to report the *model* value, 20 mm, not the 40 mm the
# scaled projection occupies on the page. A 1:1 view cannot tell those apart.
BOX = (20.0, 10.0, 5.0)
SCALE = 2.0

# The dimension is placed between two points named in *model* coordinates -- the ends of
# the top front edge. That is the whole point of item 3: these came from arithmetic on
# the box's parameters, not from asking the projection what its edges are called.
PROBE_POINTS = ((-BOX[0] / 2.0, -BOX[1] / 2.0, BOX[2]),
                (BOX[0] / 2.0, -BOX[1] / 2.0, BOX[2]))
PROBE_SPAN = BOX[0]

TOLERANCE = 1e-9


def template_path():
    """The stock ANSI A landscape template, found through the API rather than a path.

    `getResourceDir` is the installed data directory, so this resolves on any machine
    with FreeCAD on it -- but it resolves *outside the repository*, which is a finding
    in its own right and not a detail. A generated drawing that depends on a file the
    project does not carry is not reproducible from the project.
    """
    return os.path.join(App.getResourceDir(), 'Mod', 'TechDraw', 'Templates',
                        'ASME', 'ANSIA_Landscape.svg')


def build(doc):
    """A page, a template, a projected view, and two dimensions. Returns them."""
    box = doc.addObject('Part::Box', 'Box')
    box.Length, box.Width, box.Height = BOX
    doc.recompute()

    template = doc.addObject('TechDraw::DrawSVGTemplate', 'Template')
    template.Template = template_path()
    page = doc.addObject('TechDraw::DrawPage', 'Page')
    page.Template = template
    doc.recompute()

    view = doc.addObject('TechDraw::DrawViewPart', 'View')
    page.addView(view)
    view.Source = [box]
    view.Direction = V(0.0, 0.0, 1.0)
    view.XDirection = V(1.0, 0.0, 0.0)
    view.Scale = SCALE
    view.X, view.Y = 140.0, 105.0
    doc.recompute()

    # Cosmetic vertices are appended *after* the projected ones, so their index is
    # `n_geometric + i` and n_geometric moves with the variant. Reading the count here,
    # immediately before creating them, is the only form of this that survives -- a
    # literal 'Vertex4' is the face-name problem wearing a different hat.
    n_geometric = len(view.getVisibleVertexes())
    for point in PROBE_POINTS:
        view.makeCosmeticVertex3d(V(*point))
    doc.recompute()

    parametric = doc.addObject('TechDraw::DrawViewDimension', 'Parametric')
    page.addView(parametric)
    parametric.Type = 'DistanceX'
    parametric.References2D = [(view, 'Vertex%d' % n_geometric),
                               (view, 'Vertex%d' % (n_geometric + 1))]
    parametric.X, parametric.Y = 0.0, -25.0

    # Deliberately degenerate: DistanceX across a vertical edge. Nothing about this is
    # an error to TechDraw, which is exactly why section 5's H5 has to be enforced by
    # the placer -- the workbench will print a confident 0.00 mm.
    degenerate = doc.addObject('TechDraw::DrawViewDimension', 'Degenerate')
    page.addView(degenerate)
    degenerate.Type = 'DistanceX'
    degenerate.References2D = [(view, 'Edge0')]
    doc.recompute()

    return page, view, parametric, degenerate, n_geometric


def main():
    fail = []
    out = os.environ.get('SPIKE_TECHDRAW_OUT') or os.path.join(
        os.path.dirname(os.path.abspath(__file__)), 'out')
    if not os.path.isdir(out):
        os.makedirs(out)

    print('SPIKE:: TechDraw under freecadcmd')

    try:
        import TechDrawGui                                    # noqa: F401
        gui = 'imported -- unexpected'
    except Exception as exc:
        gui = str(exc)
    print('  TechDrawGui         %s' % gui)
    if 'imported' in gui:
        fail.append('TechDrawGui loaded in a console application, so the finding that '
                    'the GUI exporters are unavailable no longer holds')

    import TechDraw

    tpl = template_path()
    print('  template            %s' % tpl)
    print('  template on disk    %s' % os.path.isfile(tpl))
    if not os.path.isfile(tpl):
        fail.append('the stock template is not where getResourceDir says it is')

    paths = []
    for run in ('a', 'b'):
        doc = App.newDocument('spike_techdraw_' + run)
        page, view, parametric, degenerate, n_geometric = build(doc)

        if run == 'a':
            edges = view.getVisibleEdges()
            vertexes = view.getVisibleVertexes()
            print('  projected edges     %d' % len(edges))
            print('  projected vertexes  %d geometric + %d cosmetic'
                  % (n_geometric, len(view.CosmeticVertexes)))
            print('  first edge ends     %s'
                  % ([(v.Point.x, v.Point.y) for v in edges[0].Vertexes],))
            print('  page size           %.1f x %.1f mm'
                  % (page.Template.Width.Value, page.Template.Height.Value))
            print('  parametric dim      %s  (model span %.1f mm at %.1f:1)'
                  % (parametric.getText(), PROBE_SPAN, SCALE))
            print('  its dimension line  %s' % (parametric.getLinearPoints(),))
            print('  its arrows          %s' % (parametric.getArrowPositions(),))
            print('  degenerate dim      %s  (TechDraw raised nothing)'
                  % degenerate.getText())

            if len(edges) == 0:
                fail.append('the view projected no edges, so nothing is being drawn')
            if len(vertexes) != n_geometric + len(PROBE_POINTS):
                fail.append('cosmetic vertexes are not appended after the projected '
                            'ones, so the index rule above is wrong')
            if abs(parametric.getRawValue() - PROBE_SPAN) > TOLERANCE:
                fail.append('a dimension between two parameter-placed points reports '
                            '%.6f mm for a %.1f mm span -- the view scale is leaking '
                            'into the value' % (parametric.getRawValue(), PROBE_SPAN))
            if len(parametric.getLinearPoints()) < 2:
                fail.append('the dimension line does not read back, so an independent '
                            'checker has nothing to measure')
            if abs(degenerate.getRawValue()) > TOLERANCE:
                fail.append('the degenerate dimension is not zero, so it is not the '
                            'case the H5 rule was written for')

            # Not a failure -- a limitation, and the placer has to be built knowing it.
            if all(p.Length == 0.0 for p in parametric.getArrowPositions()):
                print('  NOTE                arrow positions are all origin headless; '
                      'the annotation extent has to be modelled, not measured')

        path = os.path.join(out, 'spike_techdraw_%s.dxf' % run)
        TechDraw.writeDXFPage(page, path)
        paths.append(path)
        App.closeDocument(doc.Name)

    body = [open(p, 'rb').read() for p in paths]
    dimensions = body[0].count(b'DIMENSION')
    print('  DXF written         %d and %d bytes' % (len(body[0]), len(body[1])))
    print('  DIMENSION entities  %d' % dimensions)
    print('  two runs identical  %s' % (body[0] == body[1]))

    if dimensions == 0:
        fail.append('the exported page carries no DIMENSION entities, so the export '
                    'drops the only thing UC-7a is for')
    if body[0] != body[1]:
        fail.append('two builds of the same page exported different bytes, so a '
                    'drawing set cannot be reviewed by diff')

    print('  %s' % ('FAIL: ' + '; '.join(fail) if fail
                    else 'ok -- headless drawings work'))
    return 1 if fail else 0


if is_entry_point(__name__):
    _code = main()
    sys.stdout.flush()
    sys.exit(_code)
